language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - echo en_US ISO-8859-1 >> /etc/locale.gen
  - echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
  - echo en_CA ISO-8859-1 >> /etc/locale.gen
  - echo en_CA.UTF-8 UTF-8 >> /etc/locale.gen
  - echo es_ES ISO-8859-1 >> /etc/locale.gen
  - echo es_ES.UTF-8 UTF-8 >> /etc/locale.gen
  - echo ru_RU ISO-8859-5 >> /etc/locale.gen
  - echo ru_RU.UTF-8 UTF-8 >> /etc/locale.gen
  - locale-gen --no-interaction
  - update-locale --no-interaction
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --exclude-group segmentation
  - vendor/bin/phpspec run
